# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /work/zain/Xilinx/alveo_u200_20232/alveo_u200_20232.srcs/sources_1/bd/design_1/ip/design_1_rst_ddr4_0_300M_0/design_1_rst_ddr4_0_300M_0.xci
# IP: The module: 'design_1_rst_ddr4_0_300M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /work/zain/Xilinx/alveo_u200_20232/alveo_u200_20232.gen/sources_1/bd/design_1/ip/design_1_rst_ddr4_0_300M_0/design_1_rst_ddr4_0_300M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ddr4_0_300M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /work/zain/Xilinx/alveo_u200_20232/alveo_u200_20232.gen/sources_1/bd/design_1/ip/design_1_rst_ddr4_0_300M_0/design_1_rst_ddr4_0_300M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ddr4_0_300M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /work/zain/Xilinx/alveo_u200_20232/alveo_u200_20232.gen/sources_1/bd/design_1/ip/design_1_rst_ddr4_0_300M_0/design_1_rst_ddr4_0_300M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ddr4_0_300M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /work/zain/Xilinx/alveo_u200_20232/alveo_u200_20232.srcs/sources_1/bd/design_1/ip/design_1_rst_ddr4_0_300M_0/design_1_rst_ddr4_0_300M_0.xci
# IP: The module: 'design_1_rst_ddr4_0_300M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /work/zain/Xilinx/alveo_u200_20232/alveo_u200_20232.gen/sources_1/bd/design_1/ip/design_1_rst_ddr4_0_300M_0/design_1_rst_ddr4_0_300M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ddr4_0_300M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /work/zain/Xilinx/alveo_u200_20232/alveo_u200_20232.gen/sources_1/bd/design_1/ip/design_1_rst_ddr4_0_300M_0/design_1_rst_ddr4_0_300M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ddr4_0_300M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /work/zain/Xilinx/alveo_u200_20232/alveo_u200_20232.gen/sources_1/bd/design_1/ip/design_1_rst_ddr4_0_300M_0/design_1_rst_ddr4_0_300M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ddr4_0_300M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
